### ISSUE TITLE
イベントコマンドのピクチャ表示がディレイ有りの時出力がおかしくなる

### ISSUE THREAD

**Issue by nakajimakotaro** [kameske/WodiLib#8]
ウディタVer2.24で
イベントコマンドのピクチャ表示が
+ ディレイ有り
+ カラーが全て100
+ 同値はfalse

の時数値変数の数が0x13になりますが、
WodiLibは0x0Fを出力します。

その結果WodiLibで出力したmpsをウディタで読み込んだ
時、カラーがおかしくなります。

ディレイなしの時や同値がtrueの時は問題ないです。
![キャプチャ](https://user-images.githubusercontent.com/2554362/79065364-bccd8b00-7cea-11ea-9c09-e961b6525316.PNG)

**Comment by kameske** [comment]
不具合のご報告ありがとうございます。

頂いた情報をもとに調査したところ、以下の条件での出力時に問題があることがわかりました。
- 自由変形ではない、かつ縦横別々拡大ではない
- カラーの値がすべて100、かつ同値 = false
- 発動ディレイ、連続ピクチャ数のいずれかを設定している。
上記の場合に本来 0x13 であるべき数値変数の値が 0x0F または 0x10 となっておりました。

上記不具合を修正した Ver 2.2.1 および Ver1.2.1 をリリースしておりますのでお手数ですがご確認ください。

**Comment by nakajimakotaro** [comment]
ありがとうございます！
こちらで試した所、正しく動作しました！

修正ありがとうございました！
